### ISSUE TITLE
SampleApplicationTest.testApi test failure

### ISSUE THREAD

**Issue by harshach** [hortonworks/registry#119]
testApis(com.hortonworks.registries.schemaregistry.examples.avro.SampleApplicationTest)  Time elapsed: 0.708 sec  <<< ERROR!
java.lang.RuntimeException: Jar /serdes-examples.jar could not be loaded
	at com.hortonworks.registries.schemaregistry.examples.avro.SampleSchemaRegistryClientApp.runCustomSerDesApi(SampleSchemaRegistryClientApp.java:181)
	at com.hortonworks.registries.schemaregistry.examples.avro.SampleApplicationTest.testApis(SampleApplicationTest.java:43)

**Comment by satishd** [comment]
I can see `SampleApplicationTest` working like below when it is run from examples module or at the root module with `mvn clean install`.
`Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.572 sec - in com.hortonworks.registries.schemaregistry.examples.avro.SampleApplicationTest`

@harshach Pl let me know if I am missing anything here.
