### ISSUE TITLE
Missing column in schema_metadata_info tables.

### ISSUE THREAD

**Issue by satishd** [hortonworks/registry#184]
Below error is thrown when a schema is inserted

```
ERROR [2017-07-14 05:13:40,609] com.hortonworks.registries.schemaregistry.webservice.SchemaRegistryResource: Error encountered while adding
104 ! org.mariadb.jdbc.internal.util.dao.QueryException: Unknown column 'validationLevel' in 'field list'
105 ! Query is: INSERT INTO schema_metadata_info (`id`, `name`, `description`, `schemaGroup`, `type`, `compatibility`, `validationLevel`, `time
106 ! at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1114)
107 ! at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:172)
108 ! at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeInternal(MariaDbClientPreparedStatement.java:230)
109 ! ... 73 common frames omitted
110 ! Causing: java.sql.SQLSyntaxErrorException: (conn:99) Unknown column 'validationLevel' in 'field list'
```

**Comment by michaelandrepearce** [comment]
@satishd you picking this up, or shall i? should be simple resolve will just need to update the create table scripts.

**Comment by michaelandrepearce** [comment]
Actually as no assignee I assume you haven't, assigned my myself

**Comment by satishd** [comment]
@michaelandrepearce Assigned myself as I am already working on this. I am testing this out now and I will raise PR soon. Your recent PR does not completely address this issue.

**Comment by michaelandrepearce** [comment]
Fair enough I'll close my pr
