### ISSUE TITLE
Creating a schema fails in postgres DB

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/registry#271]
It throws following error:

```
DEBUG [2017-10-11 10:23:50,456] com.hortonworks.registries.schemaregistry.SchemaVersionLifecycleManager: Encountered storage exception while trying to add a new version, attempting again : [1] with error: [{}]
! org.postgresql.util.PSQLException: ERROR: column "details" is of type bytea but expression is of type character varying
!   Hint: You will need to rewrite or cast the expression.
!   Position: 123
! at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
! at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
! at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
! at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
! at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
! at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
! at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:135)
! at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
! at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
! at com.hortonworks.registries.storage.impl.jdbc.provider.sql.factory.AbstractQueryExecutor$QueryExecution.executeUpdate(AbstractQueryExecutor.java:253)
! ... 75 common frames omitted
! Causing: com.hortonworks.registries.storage.exception.StorageException: org.postgresql.util.PSQLException: ERROR: column "details" is of type bytea but expression is of type character varying
!   Hint: You will need to rewrite or cast the expression.
!   Position: 123
```

After that theres some retry mechanism that keeps trying to insert the parent row and it throws duplicate key exception. If its not recoverable error, registry should not attempt to reinsert the row.

**Comment by satishd** [comment]
@arunmahadevan Can you post the complete stack trace?

**Comment by satishd** [comment]
This issue occurs due to wrong type associated with schema_version_state#details field. I have fixed this issue locally. I will raise PR once dependent #270 is merged.
