### ISSUE TITLE
getConnection throws exception if there is no active transaction

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/registry#296]
Heres the stack trace:

```
Exception in thread "main" com.hortonworks.registries.storage.exception.StorageException: com.google.common.util.concurrent.UncheckedExecutionException: com.hortonworks.registries.storage.exception.TransactionException: No active transaction is associated with the thread id : 1 
	at com.hortonworks.registries.storage.cache.impl.GuavaCache.get(GuavaCache.java:70)
	at com.hortonworks.registries.storage.cache.impl.GuavaCache.get(GuavaCache.java:39)
	at com.hortonworks.registries.storage.CacheBackedStorageManager.get(CacheBackedStorageManager.java:96)
	at com.hortonworks.streamline.streams.catalog.service.StreamCatalogService.getTopologyVersionInfo(StreamCatalogService.java:245)
	at com.hortonworks.streamline.streams.service.StreamsModule.setupPlaceholderTopologyVersionInfo(StreamsModule.java:207)
	at com.hortonworks.streamline.streams.service.StreamsModule.setupPlaceholderEntities(StreamsModule.java:203)
	at com.hortonworks.streamline.streams.service.StreamsModule.getResources(StreamsModule.java:109)
	at com.hortonworks.streamline.webservice.StreamlineApplication.registerResources(StreamlineApplication.java:298)
	at com.hortonworks.streamline.webservice.StreamlineApplication.run(StreamlineApplication.java:102)
	at com.hortonworks.streamline.webservice.StreamlineApplication.run(StreamlineApplication.java:76)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:79)
	at com.hortonworks.streamline.webservice.StreamlineApplication.main(StreamlineApplication.java:80)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.hortonworks.registries.storage.exception.TransactionException: No active transaction is associated with the thread id : 1 
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.hortonworks.registries.storage.cache.impl.GuavaCache.get(GuavaCache.java:61)
	... 14 more
Caused by: com.hortonworks.registries.storage.exception.TransactionException: No active transaction is associated with the thread id : 1 
	at com.hortonworks.registries.storage.impl.jdbc.provider.sql.factory.AbstractQueryExecutor.getConnection(AbstractQueryExecutor.java:118)
	at com.hortonworks.registries.storage.impl.jdbc.provider.sql.factory.AbstractQueryExecutor$QueryExecution.getPreparedStatement(AbstractQueryExecutor.java:360)
	at com.hortonworks.registries.storage.impl.jdbc.provider.sql.factory.AbstractQueryExecutor$QueryExecution.executeQuery(AbstractQueryExecutor.java:320)
	at com.hortonworks.registries.storage.impl.jdbc.provider.sql.factory.AbstractQueryExecutor.executeQuery(AbstractQueryExecutor.java:302)
	at com.hortonworks.registries.storage.impl.jdbc.provider.mysql.factory.MySqlExecutor.select(MySqlExecutor.java:107)
	at com.hortonworks.registries.storage.impl.jdbc.JdbcStorageManager.get(JdbcStorageManager.java:93)
	at com.hortonworks.registries.storage.cache.impl.GuavaCache$1.load(GuavaCache.java:49)
	at com.hortonworks.registries.storage.cache.impl.GuavaCache$1.load(GuavaCache.java:46)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 18 more
```

**Comment by satishd** [comment]
#297
