### ISSUE TITLE
Issue with schema registry when configuring Jar Storage to HDFS	

### ISSUE THREAD

**Issue by snemuri** [hortonworks/registry#339]
Issue with schema registry when configuring Jar Storage to HDFS 

REGISTRY.ERR
`
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info. 
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.util.StringUtils.toLowerCase(Ljava/lang/String;)Ljava/lang/String; 
at org.apache.hadoop.hdfs.server.common.HdfsServerConstants$RollingUpgradeStartupOption.getAllOptionString(HdfsServerConstants.java:80) 
at org.apache.hadoop.hdfs.server.namenode.NameNode.(NameNode.java:263) 
at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176) 
at org.apache.hadoop.hdfs.DFSClient.(DFSClient.java:678) 
at org.apache.hadoop.hdfs.DFSClient.(DFSClient.java:619) 
at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149) 
at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2591) 
at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:89) 
at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2625) 
at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2607) 
at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:368) 
at com.hortonworks.registries.common.util.HdfsFileStorage.init(HdfsFileStorage.java:62) 
at com.hortonworks.registries.webservice.RegistryApplication.getJarStorage(RegistryApplication.java:189) 
at com.hortonworks.registries.webservice.RegistryApplication.registerResources(RegistryApplication.java:134) 
at com.hortonworks.registries.webservice.RegistryApplication.run(RegistryApplication.java:67) 
at com.hortonworks.registries.webservice.RegistryApplication.run(RegistryApplication.java:57) 
at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) 
at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85) 
at io.dropwizard.cli.Cli.run(Cli.java:75) 
at io.dropwizard.Application.run(Application.java:79) 
at com.hortonworks.registries.webservice.RegistryApplication.main(RegistryApplication.java:232) 
`

*RESOLUTION*:

It seems that the registry lib has "*hadoop-common-2.5.1.jar*" instead of the latest version 2.7.x
replacing hadoop-common-2.5.1.jar with the latest one resolves the issue.

**Comment by satishd** [comment]
@snemuri Which version of registry/HDP are you using? Currently, schema-registry uses hadoop 2.7.1 dependencies. I am able to start registry successfully, which is configured with HDFS(HDP-2.6.3).

**Comment by snemuri** [comment]
@satishd , Its HDF 3.0.0.0 and my customer had HDF 3.0.2

We can see 3 different versions below. (2.5.1,2.7.1 & 2.7.3)

[root@sandbox-hdf ~]# rpm -ql registry_3_0_0_0_452-0.3.0.3.0.0.0-452.el6.noarch | grep hadoop
/usr/hdf/3.0.0.0-452/registry/libs/hadoop-annotations-2.5.1.jar
/usr/hdf/3.0.0.0-452/registry/libs/hadoop-auth-2.7.3.2.5.0.0-1245.jar
/usr/hdf/3.0.0.0-452/registry/libs/hadoop-client-2.7.1.jar
/usr/hdf/3.0.0.0-452/registry/libs/hadoop-common-2.5.1.jar
/usr/hdf/3.0.0.0-452/registry/libs/hadoop-hdfs-2.7.1.jar
/usr/hdf/3.0.0.0-452/registry/libs/hbase-hadoop-compat-1.1.0.jar
/usr/hdf/3.0.0.0-452/registry/libs/hbase-hadoop2-compat-1.1.0.jar

However i've build the master branch locally and found 2.7.1 jars. Not sure if issue is specific to HDF versions.

**Comment by satishd** [comment]
@snemuri HDF 3.0.x has phoenix dependency which was getting hadoop-2.5.1 libs.

Are they using any custom serializer/deserializer libraries in their environment other than default avro ser/des that comes with registry? If they are not then they can configure something like  below in their registry config.

```
fileStorageConfiguration:
  className: "com.hortonworks.registries.common.util.LocalFileSystemStorage"
  properties:
    directory: "/tmp/storage"
```
