### ISSUE TITLE
Registry "Jar Storage HDFS URL" does not work for Namenode HA

### ISSUE THREAD

**Issue by snemuri** [hortonworks/registry#402]
Registry is unable to resolve the nameservice of HDFS with Namenode HA is enabled. 

```
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: java.net.UnknownHostException: mynameservice
        at com.hortonworks.registries.webservice.RegistryApplication.getJarStorage(RegistryApplication.java:191)
        at com.hortonworks.registries.webservice.RegistryApplication.registerResources(RegistryApplication.java:134)
        at com.hortonworks.registries.webservice.RegistryApplication.run(RegistryApplication.java:67)
        at com.hortonworks.registries.webservice.RegistryApplication.run(RegistryApplication.java:57)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:79)
        at com.hortonworks.registries.webservice.RegistryApplication.main(RegistryApplication.java:232)
Caused by: java.lang.IllegalArgumentException: java.net.UnknownHostException: mynameservice
        at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:438)
        at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)
        at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2765)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:99)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2799)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2781)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:390)
        at com.hortonworks.registries.common.util.HdfsFileStorage.init(HdfsFileStorage.java:62)
        at com.hortonworks.registries.webservice.RegistryApplication.getJarStorage(RegistryApplication.java:189)
        ... 8 more
Caused by: java.net.UnknownHostException: mynameservice
        ... 21 more

```

**Comment by joanvr** [comment]
Did you include the core-site.xml and hdfs-site.xml in the classpath of the registry?

**Comment by snemuri** [comment]
This PR will add core-site.xml and hdfs-site.xml in registry classpath. https://github.com/hortonworks/registry/pull/403
