### ISSUE TITLE
schema-registry-client breaks when I include jersey-media-moxy

### ISSUE THREAD

**Issue by derekm** [hortonworks/registry#424]
I need to include `jersey-media-moxy` to support some JAX-RS client interfaces that I use with `jersey-proxy-client`.

I think I need to prevent your use of `jersey-client` from auto-discovering `MoxyJsonFeature`.

**Comment by derekm** [comment]
I get several exceptions with `jersey-media-moxy` on the classpath. Here is an example of one of them:

```
java.util.concurrent.ExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: An exception was thrown while processing request with message: [null]
	...
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: An exception was thrown while processing request with message: [null]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739) ~[guava-18.0.jar:?]
	at com.hortonworks.registries.schemaregistry.client.SchemaRegistryClient.addSchemaVersion(SchemaRegistryClient.java:427) ~[schema-registry-client-0.3.0-fts.jar:?]
	at com.hortonworks.registries.schemaregistry.client.SchemaRegistryClient.addSchemaVersion(SchemaRegistryClient.java:376) ~[schema-registry-client-0.3.0-fts.jar:?]
	at com.hortonworks.registries.schemaregistry.serde.AbstractSnapshotSerializer.serialize(AbstractSnapshotSerializer.java:64) ~[schema-registry-client-0.3.0-fts.jar:?]
	...
Caused by: java.lang.RuntimeException: An exception was thrown while processing request with message: [null]
	at com.hortonworks.registries.schemaregistry.client.SchemaRegistryClient.handleSchemaIdVersionResponse(SchemaRegistryClient.java:474) ~[schema-registry-client-0.3.0-fts.jar:?]
	at com.hortonworks.registries.schemaregistry.client.SchemaRegistryClient.doAddSchemaVersion(SchemaRegistryClient.java:461) ~[schema-registry-client-0.3.0-fts.jar:?]
	at com.hortonworks.registries.schemaregistry.client.SchemaRegistryClient.lambda$addSchemaVersion$1(SchemaRegistryClient.java:428) ~[schema-registry-client-0.3.0-fts.jar:?]
	...
```

**Comment by gcsaba2** [comment]
Fixed
