### ISSUE TITLE
Bootstrap script throws error when passing "drop-create" option

### ISSUE THREAD

**Issue by kamalcph** [hortonworks/registry#596]
This error happens only during the first time it downloads the MySQL driver jar and loads it in the classpath.

```
hortonworks-registry-0.7.0 $ sh bootstrap/bootstrap-storage.sh drop-create
Using Configuration file: bootstrap/../conf/registry.yaml
Downloading mysql jar from url: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.40.zip
Downloading mysql jar without using proxy.
Downloading file mysql-connector-java-5.1.40.zip into /var/folders/tt/7fd821cd1l9dsgwf75lrrn5m0000gp/T/
Copying mysql libraries into lib dir...
Unzipping downloaded mysql driver and copying
Copying file to libs /Users/builds/registry/hortonworks-registry-0.7.0/bootstrap/lib/../../libs/mysql-connector-java-5.1.40-bin.jar
mysqlJarFile bootstrap/lib/mysql-connector-java-5.1.40-bin.jar
[main] INFO org.flywaydb.core.internal.util.VersionPrinter - Flyway Community Edition 5.1.4 by Boxfuse
Tue Oct 01 17:56:14 IST 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[main] INFO org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:mysql://localhost/schema_registry (MySQL 5.7)
[main] INFO org.flywaydb.core.internal.command.DbClean - Successfully cleaned schema `schema_registry` (execution time 00:00.076s)
"drop" option successful
Using Configuration file: bootstrap/../conf/registry.yaml
Exception in thread "main" org.flywaydb.core.api.FlywayException: Unable to instantiate JDBC driver: com.mysql.cj.jdbc.Driver => Check whether the jar file is present
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.<init>(DriverDataSource.java:142)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1147)
	at org.flywaydb.core.Flyway.setDataSource(Flyway.java:712)
	at com.hortonworks.registries.storage.tool.sql.SchemaFlywayFactory.get(SchemaFlywayFactory.java:49)
	at com.hortonworks.registries.storage.tool.sql.TablesInitializer.main(TablesInitializer.java:203)
Caused by: org.flywaydb.core.api.FlywayException: Unable to instantiate class com.mysql.cj.jdbc.Driver : com.mysql.cj.jdbc.Driver
	at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:61)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.<init>(DriverDataSource.java:132)
	... 4 more
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:59)
	... 5 more
```

**Comment by kamalcph** [comment]
#597
