### ISSUE TITLE
Schema registry installation fails with ambari running as non-root user(sudo)

### ISSUE THREAD

**Issue by jatinderjawanda** [hortonworks/registry#639]
`Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/common-services/REGISTRY/0.3.0/package/scripts/registry_server.py", line 193, in <module>
    RegistryServer().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/common-services/REGISTRY/0.3.0/package/scripts/registry_server.py", line 82, in install
    self.execute_bootstrap_storage_env(params)
  File "/var/lib/ambari-agent/cache/common-services/REGISTRY/0.3.0/package/scripts/registry_server.py", line 71, in execute_bootstrap_storage_env
    Execute(params.bootstrap_storage_initevn_run_cmd + ' ' + bootstrap_storage_initevn_db_cmd , user='root')
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 263, in action_run
    returns=self.resource.returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy, returns=returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 314, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk/ ; source /usr/hdf/current/registry/conf/registry-env.sh ; /usr/hdf/current/registry/bootstrap/bootstrap-storage-initenv.sh jdbc:postgresql://192.168.141.74:5432/postgres postgres admin123 registry registry registry' returned 1. We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:`

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

`sudo: no tty present and no askpass program specified`

HDF version 3.4.1.1

**Comment by gcsaba2** [comment]
Closing due to inactivity / end of life.
